### ISSUE TITLE
mixed timezones

### ISSUE THREAD

**Issue by javiertejero** [janmyler/learnyounode-tasks#1]
you are mixing timezones for the date part (UTC) and the time part (your local timezone) here:

https://github.com/janmyler/learnyounode-tasks/blob/3bce5031c7f26ba086f2e903aaff2a66a13517cb/10-timeServer.js#L11

:)

**Comment by janmyler** [comment]
Thanks for pointing out @javiertejero! it's only that working with `Date()` objects is a bit of a pain in JavaScript, all this zero padding and zero indexing… :smile:
